### POST 유저 저장1
POST localhost:8080/users/v1
Content-Type: application/json

{
    "email": "test1@test.com",
    "username": "test username1",
    "password": "test password1"
}

### POST 유저 저장2
POST localhost:8080/users/v2
Content-Type: application/json

{
    "email": "test2@test.com",
    "username": "test username2",
    "password": "test password2"
}

curl -X POST -H "Content-Type: application/json; charset=utf-8" -d '{"email": "test2@test.com","username": "test username2","password": "test password2"}' http://127.0.0.1:8080/users/v1